### PR TITLE
Task/add test script

### PR DESCRIPTION
**Pull request by badisa**
This is an attempt to add a single command for testing. I had hoped that nosetests would run at the top level, though talking to @mczwier it sounds like it is not possible.

Quite a few tests fail on my machine (OSX) with this script, some of which I imagine are expected and others are due to my local configuration.

If anyone would point out any inconsistencies in the test with how testing is currently done, that would help a lot.

End goal is to integrate this into a CI pipeline to enable further contributions without concerns of regressions.

I know that there is this: https://github.com/westpa/west_tests though it hasn't been updated in 3 years so unsure if perhaps I should have just used that script?

### CODE REVIEW

**Comment by ltchong** [comment]
Thanks a lot for putting together this test script. The west_tests were created to test any changes to solely the w_direct and w_reweight routines, i.e. verifying that these routines for calculating kinetics observables (i.e. rate constants) still yield correct observables. 

@mczwier, @burntyellow, @synapticarbors can you please provide feedback on the test script that @badisa has created and how you would prefer testing to be done?

**Comment by mczwier** [comment]
This looks like a highly reasonable start. You may need to add parallel testing and increased timeout options for the work manager tests (either hard-coded or command-line would work). Otherwise, looks good.

**Comment by DrAuxin** [comment]
Sounds good!

**Comment by burntyellow** [comment]
I'm running your script under Travis CI but there are nosetests errors.  I'm hoping others can help debug the nosetests.  You can take a look here, https://github.com/burntyellow/westpa/tree/travis_ci.  Perhaps fork this and then you can deploy the build in travis-ci.org.

The build process uses Matt's setup.sh script and appear to work fine.  The relevant files are .travis.yml, test_install.sh, and run_tests.py.  I also updated the trajtree.py to the one in this pull request, thinking that would solve some of the errors I'm seeing.  Lastly, I hardcoded some environment variables into the your run_tests.py:

os.environ['WEST_ROOT'] = os.environ['TRAVIS_BUILD_DIR']
os.environ['OMPI_MCA_btl'] = "self,tcp"
os.environ['H5PY_DEFAULT_READONLY'] = "1"

We can discuss this later after you get a chance to take a look.

**Pull request closed without merging**
