### PR TITLE
Creating a PIP Install

### PR DESCRIPTION
**Pull request by jeremyleung521**
**Issue Number.** Is this pull request related to any outstanding issues? If so, list the issue number.  

**Describe the changes made.** A clear and concise description of what the problem is and what you did to fix it. E.g. [...] was happening and I've changed [...] to fix it.  
Setup.py, pyproject.toml, and manifest.in are modified so a source distribution can be created easily with the correct dependencies when uploaded to pypi. Instructions and notes are documented [here](https://github.com/westpa/westpa/wiki/Publishing-on-PyPI). All the `numpy` (for `scipy`) requirements are tied into the `oldest-supported-numpy` [package](https://github.com/scipy/oldest-supported-numpy) so we don't have to update that perpetually.

Also tied in a fix where GH Actions might occasionally fail due to failure with code-cov. Also tied in another fix where I forgot to change the test_env back to ubuntu-latest. We're also rolling back the restriction for numpy<=1.18.5 in the test_env.

**Goals and Outstanding Issues.** A clear and concise list of goals (to be) accomplished.  
- [x] Modify settings for a pip install
- [x] fixed some CI errors

**Major files changed.**  
- [x] MANIFEST.in
- [x] setup.py
- [x] pyproject.toml
- [x] .github/workflows/test.yaml
- [x] devtools/conda-envs/test_env.yaml

**Status.**
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Additional context.** Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by jeremyleung521** [comment]
Hi @synapticarbors, There were some dependency (and cython) errors with regards to packaging for PyPI, so I had to make some edits to the MANIFEST.in and setup.py to make sure cython/scipy/numpy are installed before the setup runs. If you could take a look at the changes and merge them into the branch, that'll be great! -- JL

**Comment by synapticarbors** [comment]
This looks reasonable, although I'm not familiar with the `fetch_build_eggs` method. From some googling, I know it was suggested in a https://github.com/pypa/pip/issues/5761#issuecomment-418395650. I'm not sure what caveats there are with using that. 

Another option would be to use the `pyproject.toml` with a proper `build-system`. See for example:
https://github.com/scikit-image/scikit-image/blob/main/pyproject.toml
https://github.com/pandas-dev/pandas/blob/master/pyproject.toml

I don't have a lot of experience with building for pip, so I'm not 100% sure though.

**Comment by jeremyleung521** [comment]
> This looks reasonable, although I'm not familiar with the `fetch_build_eggs` method. From some googling, I know it was suggested in a [pypa/pip#5761 (comment)](https://github.com/pypa/pip/issues/5761#issuecomment-418395650). I'm not sure what caveats there are with using that.
> 
> Another option would be to use the `pyproject.toml` with a proper `build-system`. See for example:
> https://github.com/scikit-image/scikit-image/blob/main/pyproject.toml
> https://github.com/pandas-dev/pandas/blob/master/pyproject.toml
> 
> I don't have a lot of experience with building for pip, so I'm not 100% sure though.

I did try doing that but I've had trouble getting that to work (and it's super confusing). It also seem to require some changes to setup.py and I didn't want to break what's already there in the setup.py, so I made the least changes using the workaround.
https://github.com/scikit-image/scikit-image/blob/main/setup.py#L173
https://github.com/pandas-dev/pandas/blob/master/setup.py#L43

[`fetch_build_eggs`](http://code.nabla.net/doc/setuptools/api/setuptools/dist/setuptools.dist.Distribution.html#setuptools.dist.Distribution.fetch_build_eggs) asks setuptools to directly download/install those requirements and is made specifically to circumvent this issue. Obviously not the nicest way (since it doesn't prompt) but gets the job done. 

Totally up to our preferences.

**Comment by jeremyleung521** [comment]
Temporary closed while I play around with things. Will be back when ready again.

**Comment by jeremyleung521** [comment]
Reopening since I was able to move the install to [`pyproject.toml`]! Detailed fixes in the top post.

**Comment by atbogetti** [comment]
@jeremyleung521 I checked this over and approve of the changes.

**Pull request merged**
