### PR TITLE
Rebasing multitool branch from current master

### PR DESCRIPTION
**Pull request by astatide**
Updating to modify/incorporate/update new tools.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@burntyellow -- your latest commit pushed all of the old large files and examples back into the repo. A fresh clone of the repo is back up to 336 MB. What is this branch exactly? I've seen several commits on this branch and I don't understand what it's purpose is.

**Comment by burntyellow** [comment]
It's a mistake.  I was trying to update my fork to the master.

**Comment by synapticarbors** [comment]
It looks like all of the examples are back in `master` now, not just the branch associated with this PR. Do you know how you're going to back this out? We're going to have to re-prune the large files again. 

As a general policy, everyone should be working with forks of the repo and all changes should go through a pull request even if you have write permission on the main repository.

**Comment by burntyellow** [comment]
commit 6c1437c1d59f3eccb46eff0a5ddbe2680da6352f
Author: Kim F. Wong <kimwong@pitt.edu>
Date:   Fri Jun 19 12:07:32 2020 -0400

    Revert "Merge branch 'master' into master"

    This reverts commit 28bb11b20fbe693f0b00f78658756d86bb250359, reversing
    changes made to b9e1be96deb588d88d69be531e7966164e16a16e.

commit 28bb11b20fbe693f0b00f78658756d86bb250359
Merge: b9e1be9 17215f2
Author: burntyellow <kimwong@pitt.edu>
Date:   Fri Jun 19 11:22:47 2020 -0400

    Merge branch 'master' into master

commit b9e1be96deb588d88d69be531e7966164e16a16e
Author: Page Harrison <page.harrison.o@gmail.com>
Date:   Thu Jun 11 12:26:34 2020 -0400

    Update README.rst

**Pull request closed without merging**
