### PR TITLE
Tools tests

### PR DESCRIPTION
**Pull request by jdrusso**
This PR implements tests for `w_run`, `w_init`, `w_truncate`, and `w_states`.

### CODE REVIEW

**Comment by jdrusso** [comment]
This conflict is because of the same change in #121 so just let me know if it's appropriate to  remove the changes from here, or to remove that PR

**Comment by synapticarbors** [comment]
@jdrusso -- just to clarify, the issue is not #121 since that hasn't been merged. It actually originates from #116. If this PR overlaps with the much less extensive #121, I would fix the merge conflict here and then ditch #121. Does that make sense?

**Comment by jdrusso** [comment]
@synapticarbors Yep, makes sense! That should be done now.

**Comment by jdrusso** [comment]
This latest set of changes starting with e8d1a59 incorporates fixtures for setting up the testing environment

**Comment by jeremyleung521** [comment]
Merged to #136.

**Pull request closed without merging**
