### PR TITLE
Add executable odld example.

### PR DESCRIPTION
**Pull request by burntyellow**

### CODE REVIEW

**Comment by mczwier** [comment]
Is this pull request combining ODLD executable and conda packaging work? It would be better to separate those into different pull requests.

**Comment by burntyellow** [comment]
It's just for the ODLD executable.  I am still working on conda 
packaging.  -Kim

**Comment by burntyellow** [comment]
Is the pull request based on branches?  I pushed today some work on the 
conda packaging to my odld_exe branch.

**Comment by ajoshpratt** [comment]
It's based on branches.  Anything you push to the branch that's involved in the pull request is considered part of the pull request.

**Comment by burntyellow** [comment]
OK.  I'll clean up the odld_exe branch later and make a separate branch for
th conda packaging.

**Pull request merged**
