### PR TITLE
w_multi_west (Multitool) Ported to WESTPA2.0

### PR DESCRIPTION
**Pull request by jeremyleung521**
**Issue Number.** Is this pull request related to any outstanding issues? If so, list the issue number.  

**Describe the changes made.** A clear and concise description of what the problem is and what you did to fix it. E.g. [...] was happening and I've changed [...] to fix it.  
I ported `w_multi_west` from the `new_multitool` branch into WESTPA2.0. This merges multiple `west.h5` files into one single `multi.h5` file for analysis. Each iteration is reweighed and normalized to contain all the segments of the corresponding iteration of every individual simulation. For instructions, see [this page](https://github.com/westpa/westpa/wiki/man:w_multi_west) in the wiki. The code is written by Audrey (@astatide) such that it requires no modification from the rest of the tools. 

The latest commits add in functionality to combine auxdata as well (instead of just pcoord). You can explicitly type in the names of each dataset using the `--aux=NAME_OF_DATASET` flag or have the ``w_multi_west`` extract all aux dataset names using the ``--auxall`` flag. Default is ``None`` since it could potentially take up a lot of memory.

It does not work with WESTPA 1.0 `west.h5` files due to the fact that bin pickle objects contain references to 1.0 imports (such as `westpa.binning`), which were moved in 2.0. 

While debugging, I found a couple of bad imports (to `westpa.binning`) in deprecated tools/code so I fixed those as well. Also found a documentation typo in data_manger.py so I fixed that.

Updated the documentation to include ``w_multi_west`` for sphinx. Also added in pytest for w_multi_west.

**Goals and Outstanding Issues.** A clear and concise list of goals (to be) accomplished.  
- [x] Port new_multitool to WESTPA 2.0
- [x] Add in functionality to combine auxdata
- [x] Add in flag to combine all auxdata
- [x] Update documentation to include w_multi_west
- [x] fixed a couple westpa.binning imports that were missed first time round in the deprecated code 
- [x] Added in pytest for w_multi_west 

**Major files changed.**  
- [x] setup.py (to include new entry point)
- [x] src/westpa/cli/tools/w_multi_west.py
- [x] src/westpa/tools/core.py 
- [x] src/westpa/tools/__init__.py 
- [x] src/westpa/cli/tools/w_ntop.py 
- [x] src/westpa/oldtools/aframe/binning.py 
- [x] doc/documentation/cli.rst
- [x] doc/documentation/cli/w_multi_west.rst
- [x] src/westpa/core/data_manager.py (for typo in documentation)
- [x] tests/refs/multi_aux_ref.h5
- [x] tests/refs/west_aux_ref.h5
- [x] tests/test_tools/conftest.py
- [x] tests/test_tools/test_w_multi_west.py

**Status.**
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Additional context.** Add any other context or screenshots about the pull request here.  
There were three lines in `w_multi_west.py` where it would be difficult to fix (flake8 error-wise) without a significant rewrite. I skipped those error with noqa instead. If someone with more coding experience would like to tackle them, please go on ahead.

Another thing is the binhash bytestring error (#142), which I just went with solution (1).

Had problems with pickle object while developing test: pickle 5 objects (made in 3.8+ with Protocol 5) are not compatible with py3.7. Something to look out for.

### CODE REVIEW

**Comment by jeremyleung521** [comment]
The latest commit adds in functionality to combine auxdata as well (instead of solely just pcoord). For now, It requires you to explicitly type in the names of each dataset using the `--aux=NAME_OF_DATASET` flag.

**Comment by atbogetti** [comment]
Hello Jeremy, I'm getting this when trying to run according to the instructions on the wiki: 
```
(base) atb43@bogetti:~/Documents/qmmm/september2020/h5s$ $WEST_ROOT/bin/w_multi_west -m . -n 2
Traceback (most recent call last):
  File "/home/atb43/Documents/qmmm/september2020/multitool-py3/lib/west_tools/w_multi_west.py", line 341, in <module>
    WMultiWest().main()
  File "/home/atb43/Documents/qmmm/september2020/multitool-py3/lib/west_tools/westtools/core.py", line 233, in main
    self.go()
  File "/home/atb43/Documents/qmmm/september2020/multitool-py3/lib/west_tools/w_multi_west.py", line 182, in go
    bin_mapper = get_bin_mapper(west, bytes(binhash, 'utf-8'))
  File "/home/atb43/Documents/qmmm/september2020/multitool-py3/lib/west_tools/w_multi_west.py", line 80, in get_bin_mapper
    mapper = pickle.loads(pkldat)
ModuleNotFoundError: No module named 'westpa.core'
```
Is this indicating I need to use WESTPA 2.0?  How would you recommend I install this tool?  Thanks!

**Comment by atbogetti** [comment]
Nevermind, I see the correct directory now.  Sorry about that.  I'll report back soon...

**Comment by atbogetti** [comment]
Tested and works.

**Pull request merged**
