### PR TITLE
Added script for installing Miniconda followed by WESTPA

### PR DESCRIPTION
**Pull request by burntyellow**
This is the script for automatically installing Miniconda followed by WESTPA referenced in the documentation

https://github.com/westpa/westpa/wiki/Installing-WESTPA

### CODE REVIEW

**Comment by mczwier** [comment]
Glad to see the pull request for this.  The script works fine on Linux where wget is available, but fails on OS X where wget is not installed. Maybe the script can use curl instead of wget if wget is not available?

Also, this may have been part of the extended discussion about the westpa conda recipe, but it was unintuitive to me to go through the miniconda/westpa installation and then further have to execute the export and source westpa.sh commands. Is there a way to ensure that the conda installation puts links in the proper place, so that merely activating the conda environment is sufficient for putting w_run (etc) on the path?

**Comment by burntyellow** [comment]
I've update the script to detect platform (Linux vs. Mac), use wget when available otherwise use curl, and automatically source westpa.sh when conda activate.  I've tested both on my Macbook pro and our cluster login node.

**Comment by burntyellow** [comment]
Added verbose comments to script detail the delineation between miniconda installation and the westpa installation.  Also added a check for the number of commandline arguments and issue usage info if not satisfied.

**Comment by mczwier** [comment]
Thanks, @burntyellow. I'll test and merge.

**Comment by burntyellow** [comment]
Fixed the case where a user inputs a relative path for the PREFIX.  I'm done done now.

**Comment by mczwier** [comment]
Kim,

This doesn't seem to run correctly if an install directory isn't specified. It fails to exit and blindly charges ahead. Do you need to `exit` instead of `return`? Does your testing protocol for this script cover all of the paths users might follow through it?

**Comment by burntyellow** [comment]
The script was not meant to be executed directly but sourced.  I added logic in the beginning to check for this and to print an error message along with Usage syntax.  An exit statement instead of a return would log you out of the remote machine if the script was sourced, so "return" is retained.

I also made the "resolving absolute paths" command more portable by getting rid of readlink, which may not be available in OSX.  Should be a bit more clueless-proof now I hope.

**Comment by burntyellow** [comment]
This script is meant to be executed on the commandline.  I'm updating the documentation as well.

**Comment by synapticarbors** [comment]
Both `source activate` and `conda activate` work with newer versions of conda that support the latter, but it's probably better to stick with the new form of how you activate an environment (but maybe leave a note about the old syntax in case someone hasn't updated).

**Comment by mczwier** [comment]
source activate fails for me, using the miniconda installed by the script.

**Comment by burntyellow** [comment]
I tested the script under RHEL7 and OSX El Capitan, and both source activate and conda activate works.  What environment does this fail?

The required modification is not as simple as replacing source with conda.  I also need to configure the shell to use "conda activate" per the warning below but it's not a big deal.  I can make the changes and test more.

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /ihome/sam/kimwong/TEMP25/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s /ihome/sam/kimwong/TEMP25/miniconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.

**Comment by mczwier** [comment]
The environment that failed was my own Linux cluster. It could be (probably _is_) because I use zsh instead of bash, but I think the more important issue is the forward-compatibility that @synapticarbors brought up. If `conda activate` is the newer option, that's the one we should use. I think leaving it to the user whether to source `conda.sh` in `.bashrc` is wise; a y/n prompt would be best. The documentation can then reflect something like "Assuming conda is configured correctly, `conda activate westpa-2017.10` will make the WESTPA tools available at the command line."

**Comment by burntyellow** [comment]
conda activate/deactivate is now the standard.  Please test soon and let me know if something comes up.  I've tested successfully on our Linux cluster and on my Mac.  Also, please take a read at the installation directions and feel free to directly make changes:

https://github.com/westpa/westpa/wiki/Installing-WESTPA

I followed @ synapticarbors's suggestion and made a note about the conda version syntax caveat.  Please change if you think there is a cleaner approach.

**Comment by mczwier** [comment]
This looks good. Unless there are other issues or comments, I think it's time to merge.

**Pull request merged**
