### PR TITLE
minor tweaks to get webng working

### PR DESCRIPTION
**Pull request by ASinanSaglam**
**Describe the changes made.** Added a couple minor imports to get adaptive voronoi binning plug-in working again. Minor bugfix while pulling bin mapper from the main HDF5 file. 

**Major files changed.**  
- `src/westpa/__init__.py`  # importing yamlcfg and extloader as well as the plug-in module westext
- `src/src/westpa/tools/binning.py` # minor bug encountered during mapper loading from HDF5 
- `src/westpa/westext/__init__.py` # adding adaptive voronoi plug-in to __init__
- `src/westpa/westext/adaptvoronoi/__init__.py` # same as above
- `src/westpa/westext/adaptvoronoi/adaptVor_driver.py` # matching the current module location of extloader

**Status.**
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the CONTRIBUTING document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Ran some basic simulations with adaptive voronoi plug-in for testing. Those will be included in the tutorial made for the tutorial paper. Sorry for the delay, I should still be on track for the tutorial notebook deadline.

### CODE REVIEW

**Comment by jpthompson17** [comment]
@ASinanSaglam @jeremyleung521 - I think there may be a conflict between the changes to `mapper_from_hdf5()` made here and in #171: 

https://github.com/westpa/westpa/commit/955aa1205fa42b2a675ac0abec6b7034efcbd1a5#commitcomment-56273146

It is important to allow passing `binhash` as either a string or bytes?

**Comment by ASinanSaglam** [comment]
@jpthompson17 hmm, it's been a long time since I made that change. This looks like my change is redundant, if I recall correctly the hashvals needs to be bytes. I might be wrong, I can take a closer look next week.

**Comment by jeremyleung521** [comment]
My thoughts here:
https://github.com/westpa/westpa/commit/955aa1205fa42b2a675ac0abec6b7034efcbd1a5#commitcomment-56274231

I created PR #191 to roll back Sinan's change in #186 first (to make sure the current branch is working), then we contemplate whether we want to switch the other changes in #171 so the code is consistent.

**Comment by jpthompson17** [comment]
Rolling back first makes sense. Merged #191.

**Pull request merged**
