### PR TITLE
Make DataManager use its own rc instead of the global one

### PR DESCRIPTION
**Pull request by SHZ66**
**Issue Number.** Is this pull request related to any outstanding issues? If so, list the issue number.  

**Describe the changes made.** A clear and concise description of what the problem is and what you did to fix it. E.g. [...] was happening and I've changed [...] to fix it.  
The data manager can use a private RC or the global one (if a custom one was not supplied when creating the data manager). This private RC is respected and used by [certain parts](https://github.com/westpa/westpa/blob/westpa2/src/westpa/core/data_manager.py#L817) of the data manager, however, not all parts. This is probably an oversight when the data manager code was reworked to allow such flexibility. This PR fixes this issue.

**Goals and Outstanding Issues.** A clear and concise list of goals (to be) accomplished.  
- [x] Make data manager always respect the private RC if supplied.

**Major files changed.**  
- [x] data_manager.py

**Status.**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Additional context.** Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by jeremyleung521** [comment]
@SHZ66 can you rebase/cherry-pick these changes to `develop` instead? All PRs should go to `develop` first. Thanks!

**Comment by SHZ66** [comment]
> @SHZ66 can you rebase/cherry-pick these changes to `develop` instead? All PRs should go to `develop` first. Thanks!

Since this is a fairly minor bug fix, changing the target seems to do the trick. Let me know if it doesn't work. I will use the `develop` branch from now on though - thanks for letting me know!

**Review by jeremyleung521 — APPROVED** [review]
LGTM!

**Comment by jeremyleung521** [comment]
@SHZ66 Seems like a lot of openeye-specific changes got merged in. <strike>(In fact it actually reverted your changes to the data manager)</strike> so you might have to make a new branch/PR.

**Comment by SHZ66** [comment]
> @SHZ66 Seems like a lot of openeye-specific changes got merged in. (In fact it actually reverted your changes to the data manager) so you might have to make a new branch/PR.

Oops! I meant to update our openeye branch and I think the online conflict solver messed up the PR. I will fix it.

**Pull request closed without merging**
