### PR TITLE
Incorporate Patrick Pisciuneri's update to the MPI work manager; add …

### PR DESCRIPTION
**Pull request by burntyellow**
…in dependency for mpi4py within setup.py. Tested on CRC HPC cluster.

### CODE REVIEW

**Comment by synapticarbors** [comment]
Not sure if we need to do it in this PR, but it would be nice to figure out how to extend the tests in https://github.com/westpa/westpa/blob/westpa-2.0-restruct/tests/test_work_managers/test_mpi.py to do more than just check in the import.

**Comment by synapticarbors** [comment]
Also, it looks like you didn't install pre-commit in your local repo. Please do that to satisfy the linter before committing:

https://pre-commit.com/#install

**Comment by phpisciuneri** [comment]
Hi @burntyellow! - I am still here and alive - hope you all are well!  Let me know if I can help in some way.

**Comment by synapticarbors** [comment]
It looks like mpi4py does not have non-windows wheels available and it is failing to build from source, which is causing the "Verify dev env" CI job to fail (since this is using pip instead of conda). 

I'm wondering if we should declare the mpi4py requirements as an "extra" (see https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) so that users aren't pulling it in by default when using pip?

**Comment by synapticarbors** [comment]
Also can we drop the "slave" naming convention and just call them "workers" or "nodes"? In the original implementation they were called "servers"/"clients".

**Comment by burntyellow** [comment]
@phpisciuneri  Hey Patrick.  Good to hear from you.  The other MPI WM was deadlocking, I believe.  I tested your's extensively and it's legit ... so we're going with it.

**Comment by synapticarbors** [comment]
@burntyellow -- thanks for making those changes. One thing about changing `is_master` to `is_manager` is that `is_master` is defined as part of the api used external to the work manager, so that should probably remain:

https://github.com/westpa/westpa/blob/2f418129d50e34def9947e0a8100278c5b2c1c6d/src/westpa/work_managers/core.py#L169-L173

and I'm guessing it needs to be available on all subclasses.

Also note that in python 3, `super()` does not need to specify arguments: 
https://www.python.org/dev/peps/pep-3135/

and it's probably best practice to just call it without arguments.

**Comment by burntyellow** [comment]
> Not sure if we need to do it in this PR, but it would be nice to figure out how to extend the tests in https://github.com/westpa/westpa/blob/westpa-2.0-restruct/tests/test_work_managers/test_mpi.py to do more than just check in the import.

Agreed.  On the Todo list.

**Comment by phpisciuneri** [comment]
> Also can we drop the "slave" naming convention and just call them "workers" or "nodes"? In the original implementation they were called "servers"/"clients".

Yes, please.  Thank you @burntyellow for making that change.

**Comment by burntyellow** [comment]
@synapticarbors.  Thanks.  I'll check on is_master and is_manager.  The test that's running is on iteration 62 of 100.

**Comment by phpisciuneri** [comment]
> The other MPI WM was deadlocking, I believe. I tested your's extensively and it's legit ... so we're going with it.

I can't remember why it didn't get merged in the first place.  I might have been having trouble with some of the example simulations (odld I believe) and didn't have the necessary domain expertise and things kind of petered out.  I apologize for that and would be really happy if this work is ultimately useful for you all.

**Comment by burntyellow** [comment]
Josh, can you merge when you get a chance?  I successfully tested against the basic_nacl_amber_MPI-WM and odld_exe_MPI-WM examples; there's a pull request for these tests for Anthony.  There is is_master and "master" used in zeromq.  We should try to update the the language there as well but probably best after the MPI work manager is merged and tested by others.

**Pull request merged**
