### PR TITLE
[WIP - do not merge] Restructure westpa into canonical python package

### PR DESCRIPTION
**Pull request by synapticarbors**
This is a work-in-progress (**do not merge**) experiment restructuring `westpa` into a more canonical python package. The goals for the prototype are:

- Make `westpa` pip installable and simplify conda packaging
- Simplify directory structure, which can be confusing since the current state of `westpa` is the result of merging what were once several independent repositories. I hope this makes the project easier to understand and more welcoming for new developers
- Remove the need to define environment variables `WEST_ROOT`, `WEST_BIN` and `WEST_PYTHON` as these will all be handled by either a conda env or pip venv. 
- Centralize testing and make it easier to run via `pytest` or other frameworks. 

To this end, I've created a `setup.py` at the top of the repo that takes care of all of the `cython` compilation and replaces all bash scripts like `w_run`, `w_init`, etc with python [console scripts via entry_points](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point). 

Most of what I have changed at this point beyond the `setup.py` is just restructuring the directory hierarchy, fixing the imports and removing imports that were not needed (there were a lot) as found by my linter. 

Given what I currently have in this branch, the following works:

1. Install `westpa` via pip:

```bash
$ conda create -n westpa_restruct python=3.7 versioneer h5py==2.10.* scipy numpy pyyaml==5.3.* pyzmq==19.0.* matplotlib-base blessings==1.7.* ipykernel cython notebook

$ conda activate westpa_resturct
$ cd <root of repo>
$ pip install -e .   # or `python setup.py develop`
```

2. Running the simple ODLD simulation. The code for that system can be found at:
https://gist.github.com/synapticarbors/b5150165bec6daa11b09c945ad9e27cb

There are minimal changes from the old example. I can run `w_pdist` and `plothist` on this and it looks good. I tried the `analysis.ipynb`, but I'm still running into some issues with `w_ipa`. 

3. Functionality of the bash script wrapper around things like `w_run` that allowed you to run `cProfile` or `line_profiler` is easily handled. For example, under the new scheme you can just run `python -m cProfile $(which w_run)` since `w_run` is just a python script now. On windows you'll need an additional shim script, but we don't support windows currently. 

4. I've added `versioneer` to handle versioning of the code and supplying `westpa.__version__` that properly tracks our git tags. 

This work was inspired by recent comments on the developer's list by @badisa and @dnlebard, so I welcome their feedback as I think it shares many common goals of their work in this area.  Of course any feedback is welcome.

### CODE REVIEW

**Comment by badisa** [comment]
Is there a conda package of this available for testing?

**Comment by synapticarbors** [comment]
@badisa I have not made a conda package for this branch. Do you need a conda package specifically, or can you just clone my fork, switch to the branch and then run `pip install -e .` while in a conda env as described in my first comment in this PR? If necessary, I think I could make a recipe that points at my git repo and then build that in Docker and then put the resulting `.bz2` file somewhere it could be downloaded, or on my own anaconda.org account. I'm not sure that's optimal because I'd have to push out a new conda release every time I make changes in the branch. Let me know though.

**Comment by badisa** [comment]
@synapticarbors I do need a conda package to test this in our cloud platform, though not a priority.

**Comment by synapticarbors** [comment]
I have all of the test suite now working except for:

- `test_mclib.py`, which has a dependency on a file from @mczwier's personal directory
-  I'm seeing `zmq.error.ZMQError: Too many open files` from `test_work_managers.test_zeromq.test_node.TestZMQNodeExternal.test_as_completed`. 
- One failure in `test_binning.TestFuncBinMapper.test_fmapper`

I'll note that the entire test suite can be run simply as:

```bash
$ nosetests -v tests
```

from the top of the repository, because I've separated the source from the tests. So this might be an alternative solution to #103 since it achieves the desired goal that necessitated it in the first place. 

I think I'm at a point to ask what are the next steps to validate this restructuring with an eye to making this acceptable to the developer community and having it merged? I'm not in a position to test this for systems that require a cluster and I'm not familiar with all of the workflows currently employed with the post-run tools. I'd love it if I could partner with a current dev/user to use this branch with their work flow to see if there are things I've missed.

**Comment by ltchong** [comment]
Thanks a lot for these helpful efforts! The framework for automatic testing through Travis is still being set up. In the meantime, the best way to test changes to WESTPA is the suite of WESTPA tutorials in the LiveCoMS article. 

@atbogetti can help with testing your code using this tutorials and let you know how it goes. 

Also useful is the testing of the kinetics tools using the ODLD propagator: https://github.com/westpa/west_tests

**Comment by synapticarbors** [comment]
@ltchong -- I attempted to revive the tests in https://github.com/westpa/west_tests. The changes are in my personal branch of that repo:

https://github.com/synapticarbors/west_tests/blob/fb-make-proper-pkg/test_kinetics.py

A few notes:
- The `test_direct` passes, but I'm getting `nan`s in `test_reweight`. I need to investigate this further.
- Running the tests uncovered two issues:
    - The `.h5` files contain pickled data that was written with the py2 version of the code. There are some incompatible characters in it that need to decoded as `latin1`, which is strange. I temporarily changed that in the upstream reader, but this might be a general problem with analyzing old `.h5` files with the new py3 code. 
    - The pickles also rely on `westpa` being structured in a certain way so that it can rebuild the objects. Since my branch moves stuff around, there is a simple alias that needs to be made so that this works (https://github.com/synapticarbors/west_tests/blob/fb-make-proper-pkg/test_kinetics.py#L19-L20)
- I found what I think is probably a bug in the current code. When I tried to load the bin definitions from the `odld/BINS` file, they were being ignored. The following line seems to miss a check for `bins_from_file`, which makes `bins_from_h5file` equal `True`, which then makes the block in `elif bins_from_file` never run:

    https://github.com/westpa/westpa/blob/master/lib/west_tools/westtools/binning.py#L325

    Checking the `git blame`, the code has been like that for 7 years, so I'm not sure how this was working before, or if no one ever really used it or if people did, they weren't actually getting the behavior they expected. I'll raise an issue on the bug tracker about this.

**Comment by jdrusso** [comment]
Hi! Exciting to see this progress on the testing front.

I have some systems I was running on our cluster here under the 2017.10 release -- I'm happy to test out compatibility. In particular, I had a lysozyme/benzene system running under both Gromacs and OpenMM that I'd be happy to test with this. 

What's the most productive way for me to test against those systems? Would it be helpful to provide a description of the workflow, fire up the 2020 release and see if it'll run it, or something else/all of the above?

**Comment by ltchong** [comment]
@jdrusso thanks a lot for being up for testing! Seeing if the restructured westpa runs for your lysozyme/benzene systems would be great along with a description of the workflow. @atbogetti is running tests with Amber so your tests with OpenMM and Gromacs would be a very helpful. 

@synapticarbors may have further suggestions for testing.

**Comment by atbogetti** [comment]
Hello,

I tried the restructured code on the basic_nacl tutorial with Amber and have run into the following problem when trying to initialize with w_init.

Traceback (most recent call last):
  File "/home/anthony/apps/anaconda3/envs/westpa_restruct/bin/w_init", line 11, in <module>
    load_entry_point('westpa', 'console_scripts', 'w_init')()
  File "/home/anthony/apps/westpa/src/westpa/cli/core/w_init.py", line 62, in entry_point
    system = westpa.rc.get_system_driver()
  File "/home/anthony/apps/westpa/src/westpa/core/_rc.py", line 497, in get_system_driver
    self._system = self.new_system_driver()
  File "/home/anthony/apps/westpa/src/westpa/core/_rc.py", line 344, in new_system_driver
    system = extloader.get_object(sysdrivername)(rc=self)
  File "/home/anthony/apps/westpa/src/westpa/core/extloader.py", line 64, in get_object
    module = load_module(modspec, path)
  File "/home/anthony/apps/westpa/src/westpa/core/extloader.py", line 30, in load_module
    (fp, pathname, desc) = imp.find_module(next_component, path)
  File "/home/anthony/apps/anaconda3/envs/westpa_restruct/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'west'

I didn't have any issues with the install instructions above.  Is there some path I should be setting in my env.sh since I am not sourcing westpa.sh anymore?

**Comment by synapticarbors** [comment]
@atbogetti I had missed some import issues in the executable propagator that should be fixed in the lastest commit I just pushed. Also note that in the basic_nacl tutorial, you will have to make a few changes (although maybe you've started to do this already). The ones that I've spotted thus far are:

- In the `init.sh` and  `run.sh`, get rid of the `$WEST_ROOT/bin/` part of the call to `w_init` and `w_run`.
- Specific to the issue you're seeing, in the `west.cfg`, you'll need to use: 
```
driver: westpa.core.systems.WESTSystem
````
- Get rid of the `WEST_PYTHON` line in `env.sh`

There are probably others that I haven't spotted, or didn't uncover since I don't have OpenMM and MDTraj installed to run the full tutorial yet. With the above changes though, I'm able to get `init.sh` to run successfully.

**Comment by atbogetti** [comment]
Thanks Josh, I was able to initialize after making those changes.  Now I'm getting this error after an iteration.  Dyamics and pcoord calculation were just fine.  Here is my west.log.

Updating system with the options from the configuration file
Maximum wallclock time: 3 days, 0:00:00

Mon Jun  1 13:18:14 2020
Iteration 1 (2 requested)
Beginning iteration 1
5 segments remain in iteration 1 (5 total)
1 of 21 (4.761905%) active bins are populated
per-bin minimum non-zero probability:       1
per-bin maximum probability:                1
per-bin probability dynamic range (kT):     0
per-segment minimum non-zero probability:   0.2
per-segment maximum non-zero probability:   0.2
per-segment probability dynamic range (kT): 0
norm = 1, error in norm = 0 (0*epsilon)
-- ERROR    [westpa.work_managers.core] -- uncaught exception in remote function
Traceback (most recent call last):
  File "/home/anthony/apps/westpa/src/westpa/work_managers/processes.py", line 61, in task_loop
    result = fn(*args, **kwargs)
  File "/home/anthony/apps/westpa/src/westpa/core/wm_ops.py", line 29, in post_iter
    propagator.finalize_iteration(n_iter, segments)
  File "/home/anthony/apps/westpa/src/westpa/core/propagators/executable.py", line 427, in finalize_iteration
    rc, rusage = self.exec_for_iteration(child_info, n_iter)
  File "/home/anthony/apps/westpa/src/westpa/core/propagators/executable.py", line 338, in exec_for_iteration
    return self.exec_child_from_child_info(child_info, template_args, environ)
  File "/home/anthony/apps/westpa/src/westpa/core/propagators/executable.py", line 247, in exec_child_from_child_info
    stderr= self.makepath(child_info['stderr'], template_args) if child_info['stderr'] else None)
  File "/home/anthony/apps/westpa/src/westpa/core/propagators/executable.py", line 220, in exec_child
    stdout = open(stdout, 'wb') if stdout else sys.stdout
NameError: name 'sys' is not defined

exception caught; shutting down
-- ERROR    [w_run] -- Traceback (most recent call last):
  File "/home/anthony/apps/westpa/src/westpa/cli/core/w_run.py", line 52, in entry_point
    sim_manager.run()
  File "/home/anthony/apps/westpa/src/westpa/core/sim_manager.py", line 646, in run
    self.finalize_iteration()
  File "/home/anthony/apps/westpa/src/westpa/core/sim_manager.py", line 404, in finalize_iteration
    self.work_manager.submit(wm_ops.post_iter, args=(self.n_iter, list(self.segments.values()))).get_result()
  File "/home/anthony/apps/westpa/src/westpa/work_managers/core.py", line 341, in get_result
    raise self._exception
NameError: name 'sys' is not defined

**Comment by synapticarbors** [comment]
@atbogetti there was just a missing import. I fixed it in the latest commit. I also go the basic_nacl tutorial running a few iterations without issue. I've committed the changes to the tutorial here:

https://github.com/synapticarbors/westpa_tutorials/tree/fb-make-proper-pkg

**Comment by atbogetti** [comment]
I can now run a few iterations successfully.  w_pdist, plothist, w_ipa also work fine, but a few errors I'm having...

w_succ gives me the following error:
/home/anthony/apps/westpa/src/westpa/oldtools/aframe/plotting.py:61: MatplotlibDeprecationWarning:
The revcmap function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use Colormap.reversed() instead.
  cm_pdr_r = matplotlib.colors.LinearSegmentedColormap('pdr_r', matplotlib.cm.revcmap(_pdr_data), 2048)
Traceback (most recent call last):
  File "/home/anthony/apps/anaconda3/envs/westpa_restruct/bin/w_succ", line 11, in <module>
    load_entry_point('westpa', 'console_scripts', 'w_succ')()
  File "/home/anthony/apps/westpa/src/westpa/cli/core/w_succ.py", line 79, in entry_point
    wsucc.process_args(args)
  File "/home/anthony/apps/westpa/src/westpa/oldtools/aframe/data_reader.py", line 52, in process_args
    westpa.rc.config.require(['west','data','west_data_file'])
NameError: name 'westpa' is not defined

and w_trace:

Traceback (most recent call last):
  File "/home/anthony/apps/anaconda3/envs/westpa_restruct/bin/w_trace", line 11, in <module>
    load_entry_point('westpa', 'console_scripts', 'w_trace')()
  File "/home/anthony/apps/westpa/src/westpa/cli/tools/w_trace.py", line 552, in entry_point
    WTraceTool().main()
  File "/home/anthony/apps/westpa/src/westpa/tools/core.py", line 111, in main
    self.go()
  File "/home/anthony/apps/westpa/src/westpa/cli/tools/w_trace.py", line 435, in go
    self.emit_trace_h5(trace, trajgroup)
  File "/home/anthony/apps/westpa/src/westpa/cli/tools/w_trace.py", line 478, in emit_trace_h5
    output_group['basis_state'] = trace.basis_state.as_numpy_record()
  File "/home/anthony/apps/westpa/src/westpa/core/states.py", line 93, in as_numpy_record
    from west.data_manager import vstr_dtype, weight_dtype, seg_id_dtype
ModuleNotFoundError: No module named 'west'

These are just some of the more common west_tools I use.  I'll do some testing with the other kinetics tools next.

**Comment by synapticarbors** [comment]
@atbogetti I just pushed more fixes to address the errors you were seeing as well as some others that I found by grepp'ing around in the code.

**Comment by atbogetti** [comment]
w_succ now works, but w_trace gives the following error:

Traceback (most recent call last):
  File "/home/anthony/apps/anaconda3/bin/w_trace", line 11, in <module>
    load_entry_point('westpa', 'console_scripts', 'w_trace')()
  File "/home/anthony/apps/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/anthony/apps/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/home/anthony/apps/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/home/anthony/apps/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/anthony/apps/westpa/src/westpa/cli/tools/w_trace.py", line 6, in <module>
    from westpa.tools import WESTTool, WESTDataReader
  File "/home/anthony/apps/westpa/src/westpa/tools/__init__.py", line 7, in <module>
    from .progress import ProgressIndicatorComponent
  File "/home/anthony/apps/westpa/src/westpa/tools/progress.py", line 2, in <module>
    from westpa.core.progress import ProgressIndicator
  File "/home/anthony/apps/westpa/src/westpa/core/progress.py", line 2, in <module>
    import threading, time, blessings #@UnresolvedImport
ModuleNotFoundError: No module named 'blessings'

**Comment by synapticarbors** [comment]
@atbogetti -- can you check if you have `blessings` installed in your environment (`conda list blessings`)? It looks like maybe it's missings since that's an external package, not an internal one that would have been moved.

**Comment by atbogetti** [comment]
Hi Josh, I have not had any other errors when running locally.  I'm now trying to get the package working with a zmq version of NaCl on GPUs.  I keep getting this error:
Tue Jun  9 09:22:49 2020
Iteration 1 (10 requested)
Beginning iteration 1
5 segments remain in iteration 1 (5 total)
1 of 21 (4.761905%) active bins are populated
per-bin minimum non-zero probability:       1
per-bin maximum probability:                1
per-bin probability dynamic range (kT):     0
per-segment minimum non-zero probability:   0.2
per-segment maximum non-zero probability:   0.2
per-segment probability dynamic range (kT): 0
norm = 1, error in norm = 0 (0*epsilon)
-- ERROR    [westpa.work_managers.zeromq.core.ZMQWorkManager.5463d2d3-7961-479e-a843-839b006a3168] -- startup phase elapsed with no contact from workers; shutting down
exception caught; shutting down
-- ERROR    [w_run] -- Traceback (most recent call last):
  File "/bgfs/ltc1/home/atb43/apps/westpa/src/westpa/cli/core/w_run.py", line 52, in entry_point
    sim_manager.run()
  File "/bgfs/ltc1/home/atb43/apps/westpa/src/westpa/core/sim_manager.py", line 626, in run
    self.prepare_iteration()
  File "/bgfs/ltc1/home/atb43/apps/westpa/src/westpa/core/sim_manager.py", line 394, in prepare_iteration
    self.work_manager.submit(wm_ops.prep_iter, args=(self.n_iter, segments)).get_result()
  File "/bgfs/ltc1/home/atb43/apps/westpa/src/westpa/work_managers/core.py", line 343, in get_result
    raise self._exception.with_traceback(self._traceback)
westpa.work_managers.zeromq.core.ZMQWorkerMissing: no workers available
Do you know where I might begin to troubleshoot this?  My setup for the zmq work manager is from here: https://github.com/burntyellow/westpa_tutorials/tree/multi-GPU/basic_nacl_amber-mpi and it has worked for me with the current westpa3 conda install.

**Comment by synapticarbors** [comment]
@atbogetti after a few small fixes, the zmq test suite passes except for:

```
test_work_managers.test_zeromq.test_work_manager.TestZMQWorkManagerInternalNone.test_shutdown_without_workers ... FAIL
test_work_managers.test_zeromq.test_work_manager.TestZMQWorkManagerInternalNone.test_shutdown_without_workers_after_submission ... FAIL
```

I think it would help to have a simple zmq example to work with that preferably used openmm so that I could test it locally. At a minimum though, could you post a link to the code you are using for this test so I can at least do a visual inspection of it and see if there's something I can spot?

**Comment by synapticarbors** [comment]
I am closing this branch in favor of #110, which will first merge this work into a branch local to the `westpa/westpa` repository and then will be later merged into `master` in a separate PR.

**Pull request closed without merging**
